[tool.poetry]
name = "DeFlip Replication Package"
version = "0.1.0"
description = "A replication package for the paper: 'Evaluating the Effectiveness of Actionable Guidance for Defect Prediction from Developers' Perspective'"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
scikit-learn = "^1.3.0"
lime = "^0.2.0.1"
seaborn = "^0.12.2"
mlxtend = "^0.22.0"
natsort = "^8.4.0"
scipy = "^1.11.2"
dice-ml = "^0.10"
bigml = "^9.6.2"

[tool.poetry.extras]
all_models = ["catboost", "xgboost"]
preprocess = ["rpy2"]

[tool.poetry.dev-dependencies]
jupyterlab = "^4.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
