[tool.poetry]
name = "deflip"
version = "0.1.0"
description = ""
authors = ["Hansae Ju <sparky@hanyang.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
scikit-learn = "^1.3.0"
jupyterlab = "^4.0.5"
lime = "^0.2.0.1"
seaborn = "^0.12.2"
rpy2 = "^3.5.14"
mlxtend = "^0.22.0"
natsort = "^8.4.0"
scipy = "^1.11.2"
dice-ml = "^0.10"
openpyxl = "^3.1.2"
bigml = "^9.6.2"
catboost = "^1.2.1.1"
imblearn = "^0.0"
xgboost = "^2.0.0"
brokenaxes = "^0.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
